image: gradle:8.2-jdk11

stages:
  - build

build:
  stage: build
  tags:
    - dind
  script:
    - gradle clean build
  artifacts:
    when: on_success
    expire_in: 30 days
    paths:
      - build/distributions/*.tar